services:
  db-postgres:
    environment:
      - POSTGRES_DB=messenger
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    image: postgres:16-alpine3.17
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d messenger -U admin" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "5555:5432"

volumes:
  postgresql-data: